### ISSUE TITLE
Kompatibilita + Behavior

### ISSUE THREAD

**Issue by LiborX** [vyskoczilova/kybernaut-ic-dic#12]
Kompatibilita:
Dosud jsem používal Musilkovo WOO ICO DIC. Zkusil jsem to deaktivovat a nainstalovat Kybernaut ICO DIC. Doposud vlozena ICa a DICa nejsou videt. Chtel bych funkcionalitu Kybernauta, ale o stavajici zaznamy nechci prijit. 
---
Behavior primlouvam se za to, abyste v nektere z budoucich verzi pridala automaticke doplneni adresy i z Administrace (editace) objednavek. Zejmena totiz z velkych firem posilaji objednavky emailem, typicky v PDF. Snazim se vse mit ve WOO a tak je pretukavam. Moc by mi to urychlilo praci.
---
Rad Vam na vyreseni obou veci financne prispeju, staci napsat kolik :-)

**Comment by LiborX** [comment]
PSC:
az nebudete mit co delat :-) hodila by se podobna funkce na PSC 
https://zvarik.cz/cs/databaze-psc

**Comment by morvy** [comment]
co sa Kompatibility tyka, prehadzovat to by asi nebolo velmi vhodne, no jednoduchym prepisanim klucov v databaze to nie je problem vsetko dostat z jedneho pluginu do druheho (aspon ku objednavkam, lebo k adresam to nema ako byt priradene). staci pristup cez phpmyadmin na databazu ..
