### ISSUE TITLE
Povinné pole o firmě pokud aktivuji checkbox: Nakupuji na firmu (volitelný)

### ISSUE THREAD

**Issue by petr-vytlacil** [vyskoczilova/kybernaut-ic-dic#29]
Lze nějak aktivovat povinnost polí o firmě pokud aktivuji checkbox: Nakupuji na firmu (volitelný). Když už vybere uživatel tuto volbu, tak ať se aktivuje nutnost tyto pole vyplnit. 

Děkuji

**Comment by vyskoczilova** [comment]
Zajímavý nápad, nebude to ale spíš na otravu? Jako, když nakupuji na firmu, tak to vyplním a když ze zvědavosti rozkliknu, tak to vyplňovat nemusím?

Jinak to můžu zapracovat do nové verze pluginu, na které pracuji

**Comment by petr-vytlacil** [comment]
No jak se to vezme, z pohledu prodejce je to důležité. Protože když už
někdo projeví zájem nákupu na firmu potřebuje to mít od něj dobře vyplněné.
Takže raději bych šel naproti prodejci a ať si to kupující odškrtne, když
to nebude chtít využít.

Teď je otázka jak to udělat, protože DIČ asi nebude povinný, jen IČ - když
už je firma tak nemusí být plátce.Chce tu logiku udělat dobře. Díval jsem
se do kódu, a zatím neznám moc hooky woo takže nevím jak to refaktorovat.

Viděl jsem akorát nějaké, ale snad ani nic nedělá.


 $fakeRequired = apply_filters( 'woolab_icdic_fake_required', false);
if($fakeRequired) {
$fields['billing']['billing_company']['label'] .= ' <abbr class="required"
title="'.__('required', 'woocommerce').'">*</abbr>';
$fields['billing']['billing_ic']['label'] .= ' <abbr class="required"
title="'.__('required', 'woocommerce').'">*</abbr>';
$fields['billing']['billing_dic']['label'] = __('Tax ID (optional, enter
only if you are a VAT payer)', 'woolab-ic-dic');
$fields['billing']['billing_dic']['label_class'] =
array('woolab-ic-dic-not-optional');
}

Děkuji

S pozdravem
Petr Vytlačil


st 27. 1. 2021 v 15:23 odesílatel Karolína Vyskočilová <
notifications@github.com> napsal:

**Comment by morvy** [comment]
s tymi required a fakeRequired som sa hral pri viacerych projektoch .. povodne som u klienta zacinal s tym, ze boli povinne vsetky 3 polia, tak sa ukazalo, ze IC DPH (DIC pre cz) nemoze byt povinne, potom sme zistili ze vlastne ani DIC nemusi byt povinne, takze vlastne okrem ICO naozaj nic nemoze ostat povinne a zial je tiez kopec ludi, co si vysvetlia pojem "Nakupujem na firmu" ze to chcu kupit ako sukromna osoba a dorucit do firmy kde pracuju, cize vtedy ICO nedovoli objednat

**Comment by vyskoczilova** [comment]
@morvy díky, @petr-vytlacil co si o to myslíte? Mně to dává celkem smysl a obávám se, že s tím nic dělat nepůjde - nebo, možná si to můžete vyřešit pro svoji cílovku na své straně, ale součástí pluginu by to být nemělo.
