### ISSUE TITLE
Smaže se IČ a DIČ při aktualizaci objednávky

### ISSUE THREAD

**Issue by pavelkocarek** [vyskoczilova/kybernaut-ic-dic#3]
Dobrý den, pokud vstoupím na editaci objednávky, kde je uložené IČ, tak jej u adresy vidím, pokud kliknu na úpravu adresy, tak je pole prázdné. Pokud na objednávce cokoli změním a provedu aktualizovat, tak se objednávka uloží již bez IČ (pokud na editaci adresy nekliknu, tak se IČ smaže stejně). Verze WP 4.9.4, Woo 3.3.3, Kybernaut IČ DIČ 1.2.0. Toto chování jsem spozoroval při aktualizaci Woo z 3.3.1 na 3.3.3. Pokud to bude možné prosím o opravu nebo nějaký nástřel, kde musím co upravit. Děkuji.

**Comment by vyskoczilova** [comment]
Dobrý den, dívala jsem se na to a neumím problém zduplikovat - mám WC 3.3.3 a poslední verzi pluginu (tu z repozitáře, co půjde brzy ven jako update, ale klidně už ji můžete testovat). Nemáte nějaké hlášky v konzoli? Netluče se tam něco jiného?

**Comment by pavelkocarek** [comment]
S verzí 1.3.0 se to chová stejně. Po vytvoření objednávky v košíku jsou v tabulce postmeta tyto dva řádky.

Upravit | Kopírovat | Odstranit | 943024 | 4520 | _billing_ic | 87033542
Upravit | Kopírovat | Odstranit | 943025 | 4520 | _billing_dic | CZ8310230665

Po aktualizaci objednávky v adminu se změní na 
Upravit | Kopírovat | Odstranit | 943024 | 4520 | _billing_ic |  
| Upravit | Kopírovat | Odstranit | 943025 | 4520 | _billing_dic |  

Chybí prostě hodnoty a přibudou řádky
Upravit | Kopírovat | Odstranit | 943033 | 4520 | _billing_billing_ic |  
Upravit | Kopírovat | Odstranit | 943034 | 4520 | _billing_billing_dic | 

Pokud zkusím uložit ič a dič, tak se v db pak vyplní jak billing_ic, tak billing_billing_ic, ale při další aktualizaci se zas uloží s prázdnou hodnotou. Console nic neukazuje. Na mě to působí, že se prostě nenačte ta hodnota pole z DB, když vlezu na objednávku a pak se uloží s prázdnou hodnotou.

**Comment by vyskoczilova** [comment]
Můžeme ještě ověřit, že postupujeme oba stejně? Zkontrolujte to prosím s přiloženým gifem. Vytvořím objednávku s vaším údajem, objednám, upravím IČO a DIČ (přidám nakonec obou 5). uložím, zaktualizuji položky v objednávce, pořád se tam stejně  ukazuje správná hodnota.

![icdic_debug_zmenahodnot](https://user-images.githubusercontent.com/3611726/37336528-f5098582-26b1-11e8-9d38-0f21103a5161.gif)


Povolíte ještě wp debug a podáváte se do logu?

```
 // Enable WP_DEBUG mode
define( 'WP_DEBUG', true );

// Enable Debug logging to the /wp-content/debug.log file
define( 'WP_DEBUG_LOG', true );

// Disable display of errors and warnings 
define( 'WP_DEBUG_DISPLAY', false );
@ini_set( 'display_errors', 0 );

// Use dev versions of core JS and CSS files (only needed if you are modifying these core files)
define( 'SCRIPT_DEBUG', true );
```

**Comment by pavelkocarek** [comment]
Moc se omlouvám, nakonec je chyba na mé straně. Při deaktivaci všech ostatních pluginů jsem přeskočil. WooCommerce Sequential Order Numbers Po jeho dodatečné deaktivaci se to začalo chovat podle očekávání. Takže teď už jen vyřešit kde je konflikt těchto pluginů. Po jeho aktivaci opět začne IČ a DIČ ukládat bez hodnoty. V příloze debug.log První tři řádky se zapsali, když byl Sequential Order Numbers deaktivovaný, zbytek, když jsem jej opětovně aktivoval a začal s objednávkou pracovat.
[debug.log](https://github.com/vyskoczilova/kybernaut-ic-dic/files/1806595/debug.log)

**Comment by pavelkocarek** [comment]
Ona ta funkce woolab_icdic_admin_billing_fields využívá get_post_meta, ale pracuje s order ID místo post ID, což se u mě díky pluginu Sequential order numbers liší. Mě pomohla změna:

`	$order = new WC_Order($post->ID);
	$order_id = trim( str_replace( '#', '', $order->get_order_number() ) );`

na
`	//$order = new WC_Order($post->ID);
	$order_id = $post->ID;`

V souboru includes/filters-actions.php řádky 272 a 273. Dle mých znalostí by to nemělo ovlivnit zbytek pluginu, ale radši porosím o kontrolu, že to je OK.

**Comment by vyskoczilova** [comment]
Máte pravdu, hlavně jsou oba řádky zbytečně komplikované, otestovala jsem a navrhovaná změna funguje jak má (bez ohledu na použitý plugin). Díky moc! Můžete ho klidně stáhnout upravený odsud a pak by to mělo být OK i s příští aktualizací.

Fixla jsem i těch několik noticek, které mi utekly při přidávání poslední feature.

Ještě jednou díky za pomoc.
