### ISSUE TITLE
Fatal error na verzii 1.6.0

### ISSUE THREAD

**Issue by Silfester** [vyskoczilova/kybernaut-ic-dic#30]
**Describe the bug**
Pri update pluginu na 1.6.0 doslo k fatalnej chybe a zhodilo cely web.
Pri pokuse o aktivovanie vyhadzuje 2 spravy:
Plugin nemohol byť aktivovaný, pretože došlo k fatálnej chybe.
Warning: require_once(/home/html/xfarby.com/public_html/wp-content/plugins/woolab-ic-dic/vendor/autoload.php): failed to open stream: No such file or directory in /home/html/xfarby.com/public_html/wp-content/plugins/woolab-ic-dic/woolab-ic-dic.php on line 28

Fatal error: require_once(): Failed opening required '/home/html/xfarby.com/public_html/wp-content/plugins/woolab-ic-dic/vendor/autoload.php' (include_path='.:/usr/share/php') in /home/html/xfarby.com/public_html/wp-content/plugins/woolab-ic-dic/woolab-ic-dic.php on line 28

![image](https://user-images.githubusercontent.com/46387128/109051980-69361700-76db-11eb-8337-81ef02b9dae5.png)

**Comment by vyskoczilova** [comment]
@Silfester vyřešeno, SVN z nějakého důvodu nepustilo do /trunk vendor složku i když tam není nikde .svnignore (ale asi nějaké defaultní wordpressové ano :/). Už by to mělo fungovat, omlouvám se za potíže.
