### ISSUE TITLE
Nakupuji na firmu - nefunguje v jiných šablonách

### ISSUE THREAD

**Issue by vyskoczilova** [vyskoczilova/kybernaut-ic-dic#31]
Relates to: #24 

V defaultních je vše OK - viz https://rateloss.tastewp.com/, ale v některých custom šablonách to nefunguje, příklad: airlux.sk. @morvy nenašel bys chvíli se na to podívat, aby to fungovalo univerzálně? Prosím, kdyžtak vás mohu s airluxem propojit.

**Comment by morvy** [comment]
toto vyzera na problem s prioritou CSS, je potrebne prefixnut to s `.woocommerce-checkout`

```
.woocommerce-checkout .woocommerce-billing-fields .woolab-ic-dic-toggle,
.woocommerce-checkout .required + .optional,
.woocommerce-checkout .woolab-ic-dic-not-optional > .optional,
.woocommerce-checkout .woolab-ic-dic-required
```

**Comment by vyskoczilova** [comment]
@morvy Díky, tak uvidíme, snad to pomůže :)

**Comment by Mattthev** [comment]
I po úpravě se překrývá toggle s poli jméno a příjmení, které nejdou vyplnit. Když dám přesunout pole Země nad toggle, tak již vše funguje správně.
Šablona Yith Remy

**Comment by vyskoczilova** [comment]
@Mattthev Můžeme se na to někde podívat? Abychom nemuseli instalovat šablonu? Případně můžete zkusit doplnit !important na konec řádek (i když tohle řešení moc nepreferuji).

**Comment by Mattthev** [comment]
@vyskoczilova Stránky: https://biodeska.cz/
Není to zatím moc odzkoušené, ale když se posune výběr země, tak snad vše funguje správně. Pokud není země posunutá, tak celá oblast jména a příjmení je překrytá přepínačem. Změním to teď do večera na tu nefungující variantu snad to bude stačit na prozkoumání. Díky.

**Comment by morvy** [comment]
problem je v tom, ze tie custom sablony nedodrziavaju urcite pravidla takze asi to budeme vychytavat dlhsie..

`
#billing_iscomp_field {
clear: both;
padding-left: 20px;
}
`

**Comment by vyskoczilova** [comment]
@morvy @Mattthev Když tohle už není funkcionalita, která by měla být součástí pluginu. - jakmile to zasahuje do vzhledu, mělo by se to řešit na úrovni dané šablony 😶 ... 
Tedy se do toho montuje bootstrap a třída .checkbox a display block, když tam není, zobrazí se všechno v pořádku. Ten původní člověk, který to hlásil se už/zatím neozval.

**Comment by morvy** [comment]
@vyskoczilova tiez som toho nazoru, ze by to nemalo byt sucastou pluginu, ma to 100% fungovat na Storefront a 2020, 2021, ostatne je zalezitost na FB skupinu a pod. Ja som doteraz problem nemal a nikdy nepouzivam tie zakladne sablony, takze chyba nie je v plugine.

**Comment by Mattthev** [comment]
Moc jsme se na to u nás nedívali, přesunutí pole země nahoru to vyřešilo... Šablona je zastaralá, takže máme i starší verzi Woocommerce. Budeme přecházet na YITH Proteo.
V každém případě moc děkujeme za tento plugin i to zaškrtávací rozšíření.

**Comment by vyskoczilova** [comment]
@Mattthev Ok, bohužel, jak píše @morvy s tím se těžko něco dělá. Každopádně pokud jste s pluginem spokojený, budu ráda, když necháte [hodnocení na stránce pluginu na WordPress.org](https://wordpress.org/support/plugin/woolab-ic-dic/reviews/#new-post).
