### ISSUE TITLE
Wrong naming of "IČ DPH"

### ISSUE THREAD

**Issue by vyskoczilova** [vyskoczilova/kybernaut-ic-dic#4]
Fix naming of "billing_dic_dph" and beware of legacy.

**Comment by morvy** [comment]
mam pocit, ze toto je vyriesene tymto: https://github.com/vyskoczilova/kybernaut-ic-dic/pull/22

**Comment by morvy** [comment]
@vyskoczilova toto by malo byt fixnute, teda ja som nepostrehol zly naming v poslednych verziach
