### ISSUE TITLE
Přepínač nakupuji na firmu - po odškrtnutí se stále odesílají data

### ISSUE THREAD

**Issue by vyskoczilova** [vyskoczilova/kybernaut-ic-dic#42]
@morvy - neměl bys čas tohle prověřit, prosím?
Díky moc!

Jedná se konkrétně o přepínač pro zobrazit/skrýt pole IČO, DIČ a Firma. 

Přepínač - Nakupuji na firmu (volitelné) zakliknu a vyplním firemní údaje, následně si to ale rozmyslím, že nechci objednávku na firmu, takže zpátky odkliknu přepínač. Nyní se vyplněné údaje tímto skryjí. Vypadá to tedy na první pohled, že se firemní údaje v objednávce neodešlou, ale bohužel ano. Pokud tedy předtím zadané údaje přímo nevymažu z kolonek, ale jenom přepínačem skryju, tak bude objednávka stejně na firmu.

**Comment by morvy** [comment]
Ano, mazat je tiez moznost, no ak nahodou zakaznik vypne a znovu zapne, lebo sa len pomylil, tak bude musiet vyplnat udaje znovu. Ale technicky je to jeho problem..

**Comment by vyskoczilova** [comment]
Fixed in  1.6.7
