### ISSUE TITLE
Překlady + povinné ičo

### ISSUE THREAD

**Issue by StudioTuzka** [vyskoczilova/kybernaut-ic-dic#47]
Ahoj, moc díky za tenhle plugin. Je skvělý 👌
Měl bych ale dvě prosby - dva dotazy.

Tvoříme platebni web pro spolek a potřeboval bych místo Název firmy, a nakupuji na firmu přehodit překlady na "nakupuji na Klub" a "název Klubu", ale když jsem šel do jazyků a koukal jsem přes poedit na překlady, tak tam tyhle možnosti nikde nejsou. Je tam spousta jiných, ale toto ne. Dá se to najít a změnit ještě někde jinde?

Druhý dotaz. Díval jsem se, že jsou části kódu, které mají dělat ič a dič jako volitelné. Ale nějak jsem nepochopil konkrétně kde a kam to zadat. Myslel jsem, že to bude v nastavení pluginu, ale tam to není. 
Byl by nějaký návod, jak udělat ičo povinné? Potřeboval bych aby to zákazníka nepustilo, dokud ič nebude vyplněno.

Moc děkuji za tvůj čas
M.G.

**Comment by vyskoczilova** [comment]
Ahoj,

pokud chcete vlastní překlad - použijte třeba Loto Translate nebo pokud je to jen pár vět: https://cs.wordpress.org/plugins/wp-override-translations/ nebo jenom snippet: https://www.businessbloomer.com/translate-single-string-woocommerce-wordpress/

Povinně ani jednu hodnotu nastavit nastavit v pluginu nelze, můžete ale použít tenhle snippet (myslím, že by měl fungovat):

```
add_filter( 'woocommerce_checkout_fields' , 'kbnt_override_checkout_fields', 100, 1 );
function kbnt_override_checkout_fields( $fields ) {   
     $fields['billing']['billing_ic']['required'] = true;
     $fields['billing']['billing_dic']['required'] = true;
     $fields['billing']['billing_dic_dph']['required'] = true;
     return $fields;
}
```

**Comment by StudioTuzka** [comment]
Opravdu velké díky. Vše funguje jak má. Použil jsem snipety jak pro povinné ičo tak pro překlad a funguje to perfektně.
Moc díky

**Comment by vyskoczilova** [comment]
Rádo se stalo :) Když mi necháš hodnocení na WordPress.org u [pluginu](https://wordpress.org/support/plugin/woolab-ic-dic/reviews/#new-post) nebo třeba na [Google Reviews](https://g.page/r/CZr0lJPn6zvUEAI/review), udělá mi to radost :)
