### ISSUE TITLE
Kompatibilita s WooCommerce 7.1 / HPOS

### ISSUE THREAD

**Issue by morvy** [vyskoczilova/kybernaut-ic-dic#50]
WooCommerce 7.1.0 ponuka moznost zapnut experimentalnu funkciu High-Performance Order Storage. Aktualna verzia Kybernaut nie je kompatibilna a teda ani HPOS nie je mozne aktivovat.

Zo strany pluginu bude potrebne upravit 3 riadky kodu (update_post_meta > $order->update_meta_data).

Nasledne sa deklaruje kompatibilita:
```
add_action( 'before_woocommerce_init', function() {
	if ( class_exists( '\Automattic\WooCommerce\Utilities\FeaturesUtil' ) ) {
		\Automattic\WooCommerce\Utilities\FeaturesUtil::declare_compatibility( 'custom_order_tables', __FILE__, true );
	}
} );
```

**Comment by vyskoczilova** [comment]
Ahoj, kromě je potřeba předělat všechno volání pro načítání a ukládání hodnot, jestli se nepletu, dávám sem odkaz a zkusím na to mrknout.

https://github.com/woocommerce/woocommerce/wiki/High-Performance-Order-Storage-Upgrade-Recipe-Book#auditing-the-code-base-for-direct-db-access-usage

**Comment by vyskoczilova** [comment]
Vyřešeno, bude v releasu 1.7.0
