### ISSUE TITLE
Skrýt políčka

### ISSUE THREAD

**Issue by vyskoczilova** [vyskoczilova/kybernaut-ic-dic#7]
https://wordpress.org/support/topic/pole-pod-zaskrtavacim-polickem

* bylo by možné schovat pole ičo, dič a název firmy pod volitelný checkbox “nakupuji na firmu”.

**Comment by vyskoczilova** [comment]
3. Ta vase pole ICO a DIC se zobrazuji v objednavce trvale,
    jak je videt z prinstrscreenu, dal jsem je nahoru + placeholder,
    aby je firemni zakaznici vyplnovali, ti jsou obecne velmi líní.
    Pan Musilek to ma ve svem pluginu o neco lepe,
   kdyz zaskrtne volbu (checkbox) NAKUP NA FIRMU
   tak se mu ta pole objevi, coz mi pripada lepsi nez
   kdybych je zobrazoval i beznym lidem.
   Zkuste si ten jeho plugin nainstalovat.

Libor K. via email

**Comment by morvy** [comment]
mam tuto funkcionalitu v ramci sablony doplnenu, mam to hodit do pluginu alebo uz to tiez mate rozpracovane?

**Comment by vyskoczilova** [comment]
@morvy pokud na to máte kapacitu, tak budu ráda za pull request, skoro bych to přidala do nastavení jako možnost zobrazovat jako doposud (default) anebo zapnout variantu s rozklikem..

**Comment by morvy** [comment]
momentalne to mam v stadiu, ze pridavam nejake classy, nejake to CSS do sablony, nieco do JS a dokopy to funguje ako plugin od Superfaktury pripadne pana Musilka .. kapacita sa najde, len aby sme na tom zbytocne nerobili obaja
