### ISSUE TITLE
ověřování IČ s mezerami

### ISSUE THREAD

**Issue by xnosek00** [vyskoczilova/kybernaut-ic-dic#8]
Dobrý den, Ivano,

  mám podnět na drobnou úpravu na pár minut. Někdy se stává, že klient zadá IČ s mezerami. V tu chvíli kybernaut-ic-dic vyhodnotí, že je IČ špatné. Jde nějak ošetřit, že by se mezery v rámci IČ při vyhodnocování v ARESu nebraly v potaz? 

  příklad vyhodnoceného IČ jako neexistující: 04 625 781
  příklad vyhodnoceného IČ jako existující: 04625781

  Nejsem si jistý, že každého klienta hned napadne, že zadal mezery v IČ. A raději bych, kdyby byl skript ošetřen na tuto chybu uživatele.

Petr

**Comment by vyskoczilova** [comment]
Dobrý den,

jmenuji se Karolína, ale stane se. Máte pravdu, poznamenám si to tu a až se vyhrabu z množství emailů nakupených po Vánocích, tak to tam zapracuju.

S pozdravem
Karolína Vyskočilová

**Comment by vyskoczilova** [comment]
Dobrý den, chyba by měla být opravena, byl byste tak hodný a stáhnul poslední verzi a vyzkoušel, jestli jsem na něco nezapomněla?

**Comment by xnosek00** [comment]
Dobrý den, Kájo,

  testoval jsem to a co se týče mezer, tak je to v pořádku. Ovšem objevil jsem problematickou chybu. Vyvoláte ji tak, že zadáte IČ a chvíli počkáte (nebudete překlikávat myší ani pracovat s tabulátorem).

  Natočil jsem to na video, aby jste hned viděla: https://www.useloom.com/share/6c58590d03c945da96458809c7898c03

**Comment by vyskoczilova** [comment]
@xnosek00 díky, zvláštní, zkusím to opravit tento týden, ale trochu nestíhám - organizuju letošní [WordCamp Praha,](https://2019.prague.wordcamp.org/). Kdybyste tam byl, dejte vědět, ráda vás uvidím.

**Comment by xnosek00** [comment]
@vyskoczilova aj, tam nebudu :) Brno a Impact Hub je mi blíže :) Díky za čas a Vaši práci :)

**Comment by vyskoczilova** [comment]
Vyřešeno v budoucím releasu 1.3.4
