### ISSUE TITLE
Slovenské DIČ sa nesprávne overuje vo VIES

### ISSUE THREAD

**Issue by morvy** [vyskoczilova/kybernaut-ic-dic#9]
Dobrý deň,

v súbore **filters-actions.php** nesprávne overujete pole DIČ, kde automaticky pri SK krajine pridávate pred DIČ "SK" a následne ho overujete vo VIES. Ak sa u nás jedná o neplatcu DPH, IČ DPH nemá a teda "SK".DIČ sa nerovná IČ DPH. Navyše, IČ DPH sa overuje samostatne neskôr voči VIES (ak je povolený)

Oprava by mala byť jednoduchá a to nahradiť riadky 171 - 175
```
$dic = ($country == 'SK') ? '' : $_POST['billing_dic'];

if ( !empty($dic) && ! $validator->validate( $dic ) ) {
	wc_add_notice( __( 'Enter a valid VAT number', 'woolab-ic-dic' ), 'error' );
}
```

Ospravedlňujem sa, že to nedávam rovno ako pull request, no s githubom zatiaľ kamarát niesom, tak snáď nabudúce..

**Comment by vyskoczilova** [comment]
Dobrý den,

díky za pozorování, kdyžtak zapracuji sama, ale jenom aby mi to bylo jasné - pokud jsem slovenský neplátce DPH, tak:

1. můžu mít DIČ a nemít přitom IČ DPH? 
2. může nastat případ, kdy DIČ != IČ DPH

**Comment by morvy** [comment]
Pokiaľ viem, tak je to takto:

1. IČO dostáva každý podnikateľský subjekt
2. DIČ dostáva každý podnikateľský subjekt, je to identifikátor pre odvod daní a odvodov
3. IČ DPH je identifikátor len pre DPH, preto neplatca toto číslo nemá

Ak IČ DPH existuje, malo by sa zhodovať s DIČ, ale to riešiť nemusíte, funguje to správne, lebo ak sa nekontroluje DIČ cez VIES pre SR, kontroluje sa IČ DPH cez VIES hneď potom, a tak to aj má byť.

**Comment by vyskoczilova** [comment]
Díky, podívám se na to a zkusím to zapracovat až budu mít chvilku. Až to bude ready (chci k tomu přihodit ještě odstraňování mezer, když už to budu posílat), pomohl byste mi to prosím zkontrolovat?

**Comment by morvy** [comment]
Samozrejme rád to pozriem aj vyskúšam funkčnosť 👍

**Comment by vyskoczilova** [comment]
@morvy Omlouvám se za zdržení, už je to opravené :) A pošlu to do dalšího release.
